# dist: trusty
sudo: false
language: elixir

elixir:
  - 1.5.0-rc.1
  - 1.4.5
  - 1.4.4
  - 1.4.3

otp_release:
  - 20.0
  - 19.3
  - 19.2
  - 19.1

cache:
  directories:
    - $HOME/.hex

before_install:
  - kerl list installations
  - export MIX_ENV=ci

script: mix espec

after_success:
  - mix coveralls.travis

after_script:
  - mix inch.report
  - mix xref warnings
  - mix xref unreachable
  - mix credo --strict
  - mix hex.outdated

matrix:
  fast_finish: true
  allow_failures:
    - otp_release: 20.0
    - elixir: 1.5.0-rc.1
